dist: jammy
language: python
python:
  - "3.9"
install:
  - "pip install -r requirements.txt"
  - "pipenv install"
  - "pipenv shell"
script:
  - coverage run test/run_tests.py
  - coverage report